FROM fedora:latest

RUN dnf -y install sudo git cabal-install ostree-devel xz-devel \
                   gobject-introspection-devel libcurl-devel \
                   ghc-haskell-gi-devel libgit2-glib-devel which hlint happy && \
    cabal update && \
    cabal install --global hpc-coveralls

# source is already bind-mounted here
WORKDIR /bdcs-api

# build the application
ENTRYPOINT ["make", "hlint", "tests"]
